wandb_version: 1

learning_rate:
  desc: null
  value: 0.005
architecture:
  desc: null
  value: MedSAM Lite
dataset:
  desc: null
  value: endovis_2018
epochs:
  desc: null
  value: 100
temperature:
  desc: null
  value: 0.07
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719934877
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
